export const SEARCH_GIF = 'SEARCH_GIF';
export const LOAD_GIF_LIST = 'LOAD_GIF_LIST';
export const LOAD_FAVORITES_LIST = 'LOAD_FAVORITES_LIST';
export const UPDATE_GIF_LIST = 'UPDATE_GIF_LIST';
export const ADD_ITEM_TO_FAVORITES = 'ADD_ITEM_FROM_FAVORITES';
export const REMOVE_ITEM_FROM_FAVORITES = 'REMOVE_ITEM_TO_FAVORITES';
